---

- name: Install base packages
  become: yes
  apt:
    name: "{{router_packages}}"
    state: latest

- name: ufw forward
  include_tasks: 'ufw_forward.yml'

- name: ufw rules
  include_tasks: 'ufw.yml'
